sudo: required
services:
  - docker

before_install:
  - docker build -t dmodzelewski/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dmodzelewski/react-test npm test

after_success:
  - docker build -t dmodzelewski/multi-client ./client
  - docker build -t dmodzelewski/multi-nginx ./nginx
  - docker build -t dmodzelewski/multi-server ./server
  - docker build -t dmodzelewski/multi-worker ./worker
  # Log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dmodzelewski/multi-client
  - docker push dmodzelewski/multi-server
  - docker push dmodzelewski/multi-nginx
  - docker push dmodzelewski/multi-worker 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-361219266943"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"